import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* Nuevos Tokens MD3 (Serene Organic Luxury) */
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'inverse-surface': 'var(--inverse-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        'surface-tint': 'var(--surface-tint)',
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary-container': 'var(--on-primary-container)',
        'inverse-primary': 'var(--inverse-primary)',
        secondary: 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        tertiary: 'var(--tertiary)',
        'on-tertiary': 'var(--on-tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        error: 'var(--error)',
        'on-error': 'var(--on-error)',
        'error-container': 'var(--error-container)',
        'on-error-container': 'var(--on-error-container)',
        'primary-fixed': 'var(--primary-fixed)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        background: 'var(--background)',
        'on-background': 'var(--on-background)',
        'surface-variant': 'var(--surface-variant)',

        /* Retrocompatibilidad (Variables antiguas) */
        'fondo-zen': 'var(--background)',
        'primario-zen': 'var(--primary)',
        'secundario-zen': 'var(--surface-container-highest)',
        'accent-gold': 'var(--inverse-primary)',
        'accent-sage': 'var(--surface-tint)',
        'deep-botanical': 'var(--on-primary-fixed)',
        'pearl-white': 'var(--on-primary)',
        'gold-primary': 'var(--accent-gold-primary)',
        'gold-light': 'var(--accent-gold-light)',
        'gold-dark': 'var(--accent-gold-dark)',
        'botanical-1': 'var(--deep-botanical-1)',
        'botanical-2': 'var(--deep-botanical-2)',
        'botanical-3': 'var(--deep-botanical-3)',
        'lavender-primary': 'var(--accent-lavender)',
        'lavender-light': 'var(--accent-lavender-light)',
        'lavender-dark': 'var(--accent-lavender-dark)',
      },
      fontFamily: {
        sans: ['var(--font-manrope)', 'sans-serif'],
        serif: ['var(--font-caslon)', 'serif'],
        'display-lg': ['var(--font-caslon)', 'serif'],
        'headline-lg': ['var(--font-caslon)', 'serif'],
        'headline-lg-mobile': ['var(--font-caslon)', 'serif'],
        'headline-md': ['var(--font-caslon)', 'serif'],
        'body-lg': ['var(--font-manrope)', 'sans-serif'],
        'body-md': ['var(--font-manrope)', 'sans-serif'],
        'label-md': ['var(--font-manrope)', 'sans-serif'],
        'label-sm': ['var(--font-manrope)', 'sans-serif'],
      },
      spacing: {
        unit: '8px',
        'container-padding': '24px',
        gutter: '16px',
        'section-gap': '64px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' }, // Assuming we duplicate the content
        },
        shimmer: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
        shimmer: 'shimmer 1.5s linear infinite',
      }
    },
  },
  plugins: [],
};

export default config;
